#application parameters
spring.application.name=kafka_demo
spring.kafka.bootstrap-servers=localhost:9092

#groups parameters
#Default group-id - not required, because listeners has own group-id
#spring.kafka.consumer.group-id=app.1
consumer.input.group-id=app.input
consumer.sink.group-id=app.sink
consumer.client.group-id=app.client

#topic settings
#topic.prefix=app_name-
topic.prefix=
input.topic.name=ewm-main-service
sink.topic.name=sink

#timestamp settings
time.format.pattern=yyyy-MM-dd HH:mm:ss

#statistic
stat.unique.ip=true
stat.window.size=300000
#stat.window.size=15000
#stat.window.size=15000
stat.punctuation.step=11000

#?????????????????????????
#spring.json.use.type.headers=false